version: '2'

services:
  app:
    build: .
    volumes:
      - ./out:/app/out
      - ./src:/app/src
    command: >-
      --retry ${RETRY_SEC}
      --postal-code ${CORONA_POSTAL_CODE}
      --code ${CORONA_CODE}
      --email ${CORONA_EMAIL}
      --salutation ${CORONA_SALUTATION}
      --street ${CORONA_STREET}
      --street-no ${CORONA_STREET_NO}
      --surname ${CORONA_SURNAME}
      --name ${CORONA_NAME}
      --city ${CORONA_CITY}
      --phone ${CORONA_PHONE}

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SES_AWS_REGION=${SES_AWS_REGION}
      - SENDER=${SENDER}
      - RECIPIENT=${RECIPIENT}
      - PYTHONUNBUFFERED=1
