version: '2'

services:
  app:
    build: .
    volumes:
      - ./out:/app/out
      - ./main.py:/app/main.py
    command: --retry 60 --postal-code ${CORONA_POSTAL_CODE} --code ${CORONA_CODE}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SES_AWS_REGION=${SES_AWS_REGION}
      - SENDER=${SENDER}
      - RECIPIENT=${RECIPIENT}
      - PYTHONUNBUFFERED=1
