version: '2'

services:
  app:
    build: .
    volumes:
      - ./out:/app/out
      - ./src:/app/src
      - ./config.yml:/app/config.yml
    command: >-
      --retry ${RETRY_SEC}
      --config ${CONFIG}

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SES_AWS_REGION=${SES_AWS_REGION}
      - SENDER=${SENDER}
      - PYTHONUNBUFFERED=1
